language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

install:
  - python setup.py install
  - pip install pytest pytest-cov flake8 coveralls pexpect paratest-dummy
  - python setup.py develop

script:
  - flake8 paratest tests --stat --count
  - py.test tests/acceptance -p no:cov
  - py.test tests/unit tests/integration --cov-report=term-missing --cov paratest

after_success:
  - coveralls

notifications:
  email:
    on_success: change
    on_failure: change
